groups:
  Jewelcrafting Chests:
  - JC_Blue_Chest
  - JC_Blue_Item_Chest
  Jewelcrafting Raw Gems:
  - Uncut_Black_Stone
  - Uncut_Blue_Stone
  - Uncut_Red_Stone
  - Uncut_Yellow_Stone
  - Uncut_Green_Stone
  - Uncut_Purple_Stone
  - Uncut_Orange_Stone
  - Uncut_blueish_Stone
  - Uncut_redish_Stone
  Jewelcrafting Cut Gems:
  - Simple_Black_Socket
  - Simple_Blue_Socket
  - Simple_Red_Socket
  - Simple_Yellow_Socket
  - Simple_Green_Socket
  - Simple_Purple_Socket
  - Simple_Orange_Socket
  - Simple_blueish_Socket
  - Simple_redish_Socket
  - Advanced_Black_Socket
  - Advanced_Blue_Socket
  - Advanced_Red_Socket
  - Advanced_Yellow_Socket
  - Advanced_Green_Socket
  - Advanced_Purple_Socket
  - Advanced_Orange_Socket
  - Advanced_blueish_Socket
  - Advanced_redish_Socket
  - Perfect_Black_Socket
  - Perfect_Blue_Socket
  - Perfect_Red_Socket
  - Perfect_Yellow_Socket
  - Perfect_Green_Socket
  - Perfect_Purple_Socket
  - Perfect_Orange_Socket
  - Perfect_blueish_Socket
  - Perfect_redish_Socket
  Jewelcrafting Broken Gems:
  - Shattered_Black_Crystal
  - Shattered_Blue_Crystal
  - Shattered_Red_Crystal
  - Shattered_Yellow_Crystal
  - Shattered_Green_Crystal
  - Shattered_Purple_Crystal
  - Shattered_Orange_Crystal
  - Shattered_redish_Crystal
  - Shattered_blueish_Crystal
  gMeats:
  - RawMeat
  - DeerMeat
  - NeckTail
  - FishRaw
  - SerpentMeat
  - WolfMeat
  - LoxMeat
  - HareMeat
  - ChickenMeat
  - BugMeat
  gFish:
  - Fish1
  - Fish10
  - Fish11
  - Fish12
  - Fish2
  - Fish3
  - Fish4_cave
  - Fish5
  - Fish6
  - Fish7
  - Fish8
  - Fish9
  gSweets:
  - CloudBerry
  - RaspBerry
  - BlueBerries
  - Honey
  gCrops:
  - Carrot
  - Turnip
  - Onion
  gShrooms:
  - Mushroom
  - MushroomYellow
  - MushroomJotunPuffs
  - MushroomMagecap
  gBuilding:
  - Stone
  - Coal
  - BlackMarble
  - Crystal
  - Wood
  - RoundLog
  - FineWood
  - YggdrasilWood
  gStackTwenty:
  - SurtlingCore
  - YmirRemains
  - Thunderstone
  - CryptKey
  - Wishbone
  - DvergrKey
  - DvergrKeyFragment
  - Wisplight
  gStackFifty:
  - AncientSeed
  - WitheredBone
  - GoblinTotem
  - Flint
  - BarleyFlour
  - SoftTissue
  - ChickenEgg
  - WolfClaw
  gStackHundred:
  - GreydwarfEye
  - BoneFragments
  - Entrails
  - LeatherScraps
  - DeerHide
  - TrollHide
  - WolfPelt
  - LoxPelt
  - ScaleHide
  - Feathers
  - Wisp
  - Carapace
  - Tar
  - Thistle
  - Dandelion
  - JuteRed
  - JuteBlue
  - WitheredBone
  - AncientSeed
  - GoblinTotem
  gStackTwoHundred:
  - Resin
  - Pukeberries
  gDropQuarter:
  - Coal
  - Honey
  - Chitin
  - CloudBerry
  - Entrails
  - BoneFragments
  - Resin
  - GreydwarfEye
  - Barley
  - Flax
  - SerpentScale
  - Wisp
  gDropThird:
  - BlackMetalScrap
  - Flint
  - RaspBerry
  - BlueBerries
  - YggdrasilWood
  - Thistle
  - Dandelion
  - RawMeat
  - DeerMeat
  - NeckTail
  - LoxMeat
  - WolfMeat
  - SerpentMeat
  - HareMeat
  - BugMeat
  - ChickenMeat
  - Ooze
  - Guck
  - Needle
  - JuteBlue
  - JuteRed
  - WolfHairBundle
  - WolfFang
  - WolfClaw
  - Sap
  - CopperOre
  - SilverOre
  gDropHalf:
  - Stone
  - Wood
  - BlackMarble
  - Obsidian
  - ElderBark
  - CopperScrap
  - TinOre
  - IronOre
  - IronScrap
  - FineWood
  - RoundLog
  - Tar
  - Crystal
  - Feathers
  - Bilebag
  - Bloodbag
  - Carapace
  - Mandible
  - Chain
  - FreezeGland
  - GiantBloodSack
  - GoblinTotem
  - LeatherScraps
  - RoyalJelly
  - Ruby
  - Amber
  - AmberPearl
  - SoftTissue
  - DeerHide
  - TrollHide
  - WolfPelt
  - LoxPelt
  - ScaleHide
  - Root
  gDropDouble:
  - Acorn
  - BirchSeeds
  - FirCone
  - PineCone
  gFloats:
  - armor
  - weapon
  - ammo
  - equipment
  - shield
  gPortals:
  - Ironpit
  gBackpacks:
  - Explorers Satchel
  - Builders Satchel
  - Explorers Backpack
  - Builders Backpack
  - Portable Hole
  - Shattered Backpack of Portability
  - Simple Backpack of Portability
  - Advanced Backpack of Portability
  - Perfect Backpack of Portability
  - Mythical Backpack of Portability

#Coins get special treatment.
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
coins:
  stack: 5000
  weight factor: 0.33

#Special category `seeds`
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
seed:
  stack: 200

#Special category `valuable`
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
valuable:
  stack: 100

#Special category `trophy`
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
trophy:
  stack: 50
  weight factor: 0.33

#Special category `boss trophy`
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
boss trophy:
  stack: 50
  weight factor: 0.33

#General QoL
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
gFloats:
  floating: yes
gBackpacks:
  floating: yes

gPortals:
  teleportable: yes

gBuilding:
  stack: 150
  weight factor: 0.75

wood:
  stack: 150

#QoL Drop Increase
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
gCrops:
  amount: 1.1

gShrooms:
  amount: 1.33

gDropQuarter:
  amount: 1.25

gDropThird:
  amount: 1.33

gDropHalf:
  amount: 1.5

gDropDouble:
  amount: 2.02

#Jewelcrafting
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Jewelcrafting Chests:
  stack: 20

Jewelcrafting Raw Gems:
  stack: 50
  amount: 1.1

Jewelcrafting Cut Gems:
  stack: 50

Jewelcrafting Broken Gems:
  stack: 200

#QoL Stack Increase
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
gMeats:
  stack: 50

gSweets:
  stack: 100

gShrooms:
  stack: 100

gCrops:
  stack: 100

gFish:
  stack: 20

gStackTwenty:
  stack: 20

gStackFifty:
  stack: 50

gStackHundred:
  stack: 100

gStackTwoHundred:
  stack: 200

# Example ItemConfig.yml
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# Predefined groups:
# all, ore, metal, food, potions, woods, trophy, boss trophy, valuable, seed, crop, stackable.
# pants, chest, helmet, cape, armor.
# axes, clubs, knives, pickaxes, polearms, spears, swords, bows, crossbows, weapon, arrows, bolts, ammo.
# round shield, tower shield, shield.
# special (fishing rod and megingjord), tool, equipment.

# Things you can change: amount, weight, weight factor, stack, stack factor, pickup, floating, teleportable, loss.
# Things you can configure per world level: amount, pickup, teleportable, loss.